INSERT INTO `streets` (`id`, `city_id`, `name`, `created_at`, `updated_at`) VALUES
	(1, 1, 'Avenida Paraná - Centro', NOW(), NOW()),
	(2, 343, 'Rua Nossa Senhora de Fátima  - Centro', NOW(), NOW()),
	(3, 98, 'Avenida Getúlio Vargas  - Centro', NOW(), NOW()),
	(4, 404, 'Rua do Comércio - Centro', NOW(), NOW()),
	(5, 99, 'Avenida João Felipe  - Centro', NOW(), NOW()),
	(6, 28, 'Avenida Sete de Setembro - Centro', NOW(), NOW()),
	(7, 431, 'Rua Rio Grande do Sul - Centro', NOW(), NOW()),
	(8, 432, 'Rua Pedro Mazzaro - Centro', NOW(), NOW()),
	(9, 433, 'Praça Otacílio Pereira Nobre - Centro', NOW(), NOW()),
	(10, 434, 'Avenida Doutor Couto Junior - Centro', NOW(), NOW()),
	(11, 486, 'Rua José Lins do Rego - Maria Regina', NOW(), NOW()),
	(12, 486, 'Avenida Contorno - Setor Central', NOW(), NOW()),
	(13, 306, 'Rua Joaquim Bernardo de Aguiar - Centro', NOW(), NOW()),
	(14, 379, 'Rua Guimaraes Rosa - Centro', NOW(), NOW()),
	(15, 11, 'Avenida Guarani - Centro', NOW(), NOW()),
	(16, 38, 'Praça Presidente Kennedy - Centro', NOW(), NOW()),
	(17, 292, 'Avenida Um - Santos Dumont', NOW(), NOW()),
	(18, 435, 'Rua Arthur Robton - Centro', NOW(), NOW()),
	(19, 405, 'Rua Rio Branco - Centro', NOW(), NOW()),
	(20, 2, 'Rua Dom Giocondo Maria Grotte - Centro', NOW(), NOW()),
	(21, 100, 'Rua Primo Luiz Baptista - Niterói', NOW(), NOW()),
	(22, 436, 'Rua Osório Machado  - Centro', NOW(), NOW()),
	(23, 437, 'Rua do Café  - Centro', NOW(), NOW()),
	(24, 438, 'Rua Santa Catarina - Centro', NOW(), NOW()),
	(25, 238, 'Avenida Humberto de Abreu Frazão  - Centro', NOW(), NOW()),
	(26, 114, 'Avenida Anicuns - Setor Irani', NOW(), NOW()),
	(27, 406, 'Avenida Barriga Verde 627 Loja - Centro', NOW(), NOW()),
	(28, 407, 'Rua Xavantes - Centro', NOW(), NOW()),
	(29, 39, 'Praça Ruy Barbosa - Centro', NOW(), NOW()),
	(30, 439, 'Avenida Vinte e Um de Março - Centro', NOW(), NOW()),
	(31, 408, 'Rua Paraná - Centro', NOW(), NOW()),
	(32, 215, 'Rua Antônio Maria Coelho  - Centro', NOW(), NOW()),
	(33, 115, 'Rua Professor Aristoclides Teixeira 6 Quadra 51 - Jardim Barcelona', NOW(), NOW()),
	(34, 167, 'Rua do Comércio 119 Lote A - Centro', NOW(), NOW()),
	(35, 308, 'Rua Tiago Marques Barbosa 384 Quadra 24 Lote 384 - Centro', NOW(), NOW()),
	(36, 410, 'Rua Quirino Longo - Centro', NOW(), NOW()),
	(37, 239, 'Rua Paulo Begot - Centro', NOW(), NOW()),
	(38, 40, 'Praça Sete de Setembro - Centro', NOW(), NOW()),
	(39, 85, 'Praça Monsenhor José Cândido - Centro', NOW(), NOW()),
	(40, 391, 'Rua Prefeito Severino Bezerra Cabral - Centro', NOW(), NOW()),
	(41, 391, 'Avenida Ville Roy - Centro', NOW(), NOW()),
	(42, 168, 'Rua da Matriz - Centro', NOW(), NOW()),
	(43, 29, 'Rua Emanuel Mafra - Centro', NOW(), NOW()),
	(44, 41, 'Praça Ruy Barbosa - Centro', NOW(), NOW()),
	(45, 440, 'Rodovia José Sartorelli 2105 Quilômetro 2 - Santo Antonio', NOW(), NOW()),
	(46, 169, 'Rua dos Jambeiros - Centro', NOW(), NOW()),
	(47, 392, 'Rua Olívio Villefort  - Centro', NOW(), NOW()),
	(48, 392, 'Rua da Damásio Vicente Silva  - Centro', NOW(), NOW()),
	(49, 411, 'Rua Vereador Pedro Merizio - Centro', NOW(), NOW()),
	(50, 240, 'Avenida Castelo Branco - Centro', NOW(), NOW()),
	(51, 3, 'Avenida Prefeito Rolando Moreira - Centro', NOW(), NOW()),
	(52, 97, 'SBN Quadra 1 Bloco A - Asa Norte', NOW(), NOW()),
	(53, 241, 'Praça Capitão Dário Furtado - Centro', NOW(), NOW()),
	(54, 4, 'Rua Expedito Pereira de Souza - Centro', NOW(), NOW()),
	(55, 170, 'Rua da Bandeira - Centro', NOW(), NOW()),
	(56, 441, 'Rua Cônego Motta  - Centro', NOW(), NOW()),
	(57, 442, 'Rua Engenheiro Carlos Roberto Carboenin - Vila Pantaleão', NOW(), NOW()),
	(58, 116, 'Rua Capitão João Crisóstomo - Setor Central', NOW(), NOW()),
	(59, 380, 'Avenida Tancredo Neves - Centro', NOW(), NOW()),
	(60, 412, 'Rua Marechal Floriano Peixoto - Centro', NOW(), NOW()),
	(61, 443, 'Rua Marechal Deodoro - Centro', NOW(), NOW()),
	(62, 118, 'Avenida Campos Verdes - Setor Central', NOW(), NOW()),
	(63, 42, 'Praça Quinze de Novembro - Centro', NOW(), NOW()),
	(64, 444, 'Rua Barão do Rio Branco - Centro', NOW(), NOW()),
	(65, 413, 'Rua Machado de Assis 542 Loja - Centro', NOW(), NOW()),
	(66, 5, 'Rua Ocimar Tessinari - Conquista', NOW(), NOW()),
	(67, 394, 'Avenida Doutor Zanny - Centro', NOW(), NOW()),
	(68, 120, 'Avenida Anestar Clemente da Silva - Setor Central', NOW(), NOW()),
	(69, 395, 'Rodovia BR-210 km 01 - Centro', NOW(), NOW()),
	(70, 45, 'Rodovia BR 235 - Ouricuri', NOW(), NOW()),
	(71, 86, 'Praça Horácio Bessa - Centro', NOW(), NOW()),
	(72, 86, 'Avenida Brasil - Centro', NOW(), NOW()),
	(73, 46, 'Praça da Liberdade - Riacho da Légua', NOW(), NOW()),
	(74, 445, 'Rua Ceará - Centro', NOW(), NOW()),
	(75, 171, 'Rua do Comércio - Centro', NOW(), NOW()),
	(76, 87, 'Rua Eduardo Mota - Centro', NOW(), NOW()),
	(77, 446, 'Rua Altino Arantes - Centro', NOW(), NOW()),
	(78, 332, 'Rua Doutora Josefina Gasparian 61 Loja - Centro', NOW(), NOW()),
	(79, 447, 'Rua XV de Novembro - Centro', NOW(), NOW()),
	(80, 6, 'Rua Rego Barros - Centro', NOW(), NOW()),
	(81, 6, 'Avenida Senador Souza Naves - Centro', NOW(), NOW()),
	(82, 6, 'Rua General Neto - Centro', NOW(), NOW()),
	(83, 345, 'Praça Desembargador Tomaz Salustino - Centro', NOW(), NOW()),
	(84, 260, 'Rua Tenente Ireneu Lacerda - Centro', NOW(), NOW()),
	(85, 172, 'Rua Dorcília Cândia de Jesus - Setor Central', NOW(), NOW()),
	(86, 172, 'Avenida Davi Alves Silva - Centro', NOW(), NOW()),
	(87, 314, 'Avenida Padre Joaquim Nonato - Centro', NOW(), NOW()),
	(88, 448, 'Rua José Bonifácio  - Centro', NOW(), NOW()),
	(89, 48, 'Rua Raimundo da Conceição Tabireza - Centro', NOW(), NOW()),
	(90, 101, 'Rua Maria Gomes de Aguiar - Centro', NOW(), NOW()),
	(91, 449, 'Praça Dom Bosco - Centro', NOW(), NOW()),
	(92, 488, 'Avenida CODESPAR 808 - Setor Central', NOW(), NOW()),
	(93, 346, 'Rua Otília Jácome  - Centro', NOW(), NOW()),
	(94, 124, 'Avenida Rio do Peixe - Setor Central', NOW(), NOW()),
	(95, 316, 'Praça Santa Teresinha 86 Térreo Térreo - Matias', NOW(), NOW()),
	(96, 450, 'Rua Maria Perpétua Piedade Gonçalves  - Centro', NOW(), NOW()),
	(97, 451, 'Rua Alfredo Lanzi - Centro', NOW(), NOW()),
	(98, 126, 'Rua Cinco - Setor Central', NOW(), NOW()),
	(99, 483, 'Avenida Valdenice Gomes da Siilva - Centro', NOW(), NOW()),
	(100, 483, 'Avenida Petronilio Menezes De Cotia - Tancredo Neves', NOW(), NOW()),
	(101, 173, 'Avenida Brasil - Centro', NOW(), NOW()),
	(102, 452, 'Praça Independência - Vila Romanópolis', NOW(), NOW()),
	(103, 49, 'Praça Pompílio Céo - Centro', NOW(), NOW()),
	(104, 261, 'Rua José Mariano Barbosa - Centro', NOW(), NOW()),
	(105, 453, 'Rua João Pereira Dias  - Centro', NOW(), NOW()),
	(106, 454, 'Alameda Gulla 373 - Centro', NOW(), NOW()),
	(107, 361, 'Avenida Borges de Medeiros - Centro', NOW(), NOW()),
	(108, 174, 'Rua Vereador José Andrade  - Centro', NOW(), NOW()),
	(109, 175, 'Rua 7 de Setembro - Centro', NOW(), NOW()),
	(110, 127, 'Rua João de Oliveira Gouveia  - Setor Central', NOW(), NOW()),
	(111, 347, 'Rua Manoel Salviano - Centro', NOW(), NOW()),
	(112, 177, 'Rua Santa Rita - Centro', NOW(), NOW()),
	(113, 178, 'Avenida 11 de Março  - Centro', NOW(), NOW()),
	(114, 381, 'Avenida Pedras Brancas - Centro', NOW(), NOW()),
	(115, 102, 'Rua São José - Centro', NOW(), NOW()),
	(116, 179, 'Rua Colaço Veras  - Centro', NOW(), NOW()),
	(117, 181, 'Rua do Comércio 1371-B - Centro', NOW(), NOW()),
	(118, 362, 'Avenida Santa Cruz - Centro', NOW(), NOW()),
	(119, 294, 'Rua José Gonçalves de Santana - Porta Florada', NOW(), NOW()),
	(120, 363, 'Avenida José Loureiro da Silva - Centro', NOW(), NOW()),
	(121, 364, 'Avenida Borges de Medeiros - Centro', NOW(), NOW()),
	(122, 455, 'Avenida Coronel Quito - Centro', NOW(), NOW()),
	(123, 396, 'Rua Francisco das Chagas Magalhães  - Centro', NOW(), NOW()),
	(124, 182, 'Rua Maria Livino - Centro', NOW(), NOW()),
	(125, 333, 'Rua Olívia Faria  - Centro', NOW(), NOW()),
	(126, 16, 'Rua Laurita Almeida Barbosa - Centro', NOW(), NOW()),
	(127, 216, 'Avenida Reynaldo Massi - Centro', NOW(), NOW()),
	(128, 128, 'Praça Daguiberto Caetano Pereira - Setor Central', NOW(), NOW()),
	(129, 103, 'Praça Hilda Garcia - Centro', NOW(), NOW()),
	(130, 129, 'Rua Joaquim G. Pádua  - Setor Central', NOW(), NOW()),
	(131, 262, 'Rua Adalberto Pereira de Lima - Centro', NOW(), NOW()),
	(132, 184, 'Rua 13 de Maio - Centro', NOW(), NOW()),
	(133, 348, 'Rua Santos Dumont - Centro', NOW(), NOW()),
	(134, 349, 'Rua Doutor Sílvio B. de Melo  - Centro', NOW(), NOW()),
	(135, 17, 'Rua Tancredo Neves - Agreste', NOW(), NOW()),
	(136, 489, 'Avenida Tertuliano Santos - Setor Central', NOW(), NOW()),
	(137, 88, 'Rua Major Idelfonso - Centro', NOW(), NOW()),
	(138, 263, 'Rua Presidente João Pessoa - Centro', NOW(), NOW()),
	(139, 52, 'Avenida Doutor Edilson Pontes - Centro', NOW(), NOW()),
	(140, 18, 'Avenida Coaracy Nunes - Central', NOW(), NOW()),
	(141, 53, 'Avenida Gabriel Dantas de Novaes - Centro', NOW(), NOW()),
	(142, 19, 'Rua Veiga Cabral - Mazagão', NOW(), NOW()),
	(143, 317, 'Rua Humaitá  - Centro', NOW(), NOW()),
	(144, 89, 'Rua José Sobreira da Cruz  - Centro', NOW(), NOW()),
	(145, 130, 'Avenida Rio Verde - Setor Central', NOW(), NOW()),
	(146, 132, 'Avenida Alipio Antônio de Paiva - Setor Central', NOW(), NOW()),
	(147, 90, 'Rua Coronel José Epifânio - Centro', NOW(), NOW()),
	(148, 397, 'Avenida Nossa Senhora de Fátima  - Centro', NOW(), NOW()),
	(149, 217, 'Praça Adolfo Alves Barreto - Centro', NOW(), NOW()),
	(150, 217, 'Rua Francisco Ferreira - Setor Central', NOW(), NOW()),
	(151, 490, 'Rua Doutor Raul Travassos - Centro', NOW(), NOW()),
	(152, 490, 'Praça da Bandeira - Setor Central', NOW(), NOW()),
	(153, 218, 'Avenida Iguatemi - Centro', NOW(), NOW()),
	(154, 398, 'Avenida Maurício Hambert - Centro', NOW(), NOW()),
	(155, 219, 'Rua Cassiano Leal Pael - Centro', NOW(), NOW()),
	(156, 220, 'Avenida Eurico Soares de Andrade - Centro', NOW(), NOW()),
	(157, 137, 'Rua Santos Dumont - Centro', NOW(), NOW()),
	(158, 382, 'Rua Rui Barbosa - Centro', NOW(), NOW()),
	(159, 55, 'Avenida Bernardino Rodrigues de Matos - Centro', NOW(), NOW()),
	(160, 365, 'Rua São Nicolau - Centro', NOW(), NOW()),
	(161, 351, 'Rua Antônio Viana Barbosa  - Centro', NOW(), NOW()),
	(162, 244, 'Avenida Treze de Maio - Centro', NOW(), NOW()),
	(163, 456, 'Rua Sete de Setembro - Centro', NOW(), NOW()),
	(164, 56, 'Rua Gildasio Souza - Centro', NOW(), NOW()),
	(165, 56, 'Avenida Quatorze de Dezembro - Centro', NOW(), NOW()),
	(166, 335, 'Avenida José Ruiz Bolea - Centro', NOW(), NOW()),
	(167, 140, 'Avenida Sargento Leontino - Setor Central', NOW(), NOW()),
	(168, 457, 'Avenida Adolfo Rodrigues - Centro', NOW(), NOW()),
	(169, 458, 'Rua Ozias Ávila de Menezes  - Centro', NOW(), NOW()),
	(170, 57, 'Praça São José - Centro', NOW(), NOW()),
	(171, 336, 'Rodovia Presidente Dutra - Prata', NOW(), NOW()),
	(172, 142, 'Avenida Independência  - Setor Central', NOW(), NOW()),
	(173, 459, 'Avenida Nosso Senhor do Bonfim 472 Box - Centro', NOW(), NOW()),
	(174, 245, 'Avenida Brasil 15 Quilômetro  - Centro', NOW(), NOW()),
	(175, 58, 'Praça do Comércio - Centro', NOW(), NOW()),
	(176, 460, 'Rua Pedro Pereira Dias - Centro', NOW(), NOW()),
	(177, 383, 'Avenida Deziderio Domingos Lopes - Centro', NOW(), NOW()),
	(178, 461, 'Rua Rio Branco - Centro', NOW(), NOW()),
	(179, 491, 'Rua Jeremias Pereira - Centro', NOW(), NOW()),
	(180, 491, 'Rua Presidente João Pessoa - Centro', NOW(), NOW()),
	(181, 491, 'Avenida Goiás  - Setor Central', NOW(), NOW()),
	(182, 188, 'Rua do Comércio - Centro', NOW(), NOW()),
	(183, 32, 'Rua 07 de Setembro - Centro', NOW(), NOW()),
	(184, 492, 'Rua 22 de Abril - Setor Central', NOW(), NOW()),
	(185, 92, 'Rua Manuel Peixoto - Centro', NOW(), NOW()),
	(186, 318, 'Avenida Valdir Leite - Centro', NOW(), NOW()),
	(187, 318, 'Avenida Santa Rita 826 Sala - Centro', NOW(), NOW()),
	(188, 384, 'Rua Carolino Machado - Centro', NOW(), NOW()),
	(189, 384, 'Avenida Ayrton Senna - Centro', NOW(), NOW()),
	(190, 104, 'Praça Jones dos Santos Neves - Centro', NOW(), NOW()),
	(191, 414, 'Praça João Stival - Setor Central', NOW(), NOW()),
	(192, 414, 'Rua Doutor Cesare Tibaldeschi 186 Sala - Centro', NOW(), NOW()),
	(193, 61, 'Avenida Oceânica - Centro', NOW(), NOW()),
	(194, 462, 'Rua Major João Batista Novais  - Centro', NOW(), NOW()),
	(195, 493, 'Avenida Primeiro de Maio - Setor Central', NOW(), NOW()),
	(196, 33, 'Avenida João Paulo  - Centro', NOW(), NOW()),
	(197, 494, 'Rua Doutor João de Abreu  - Setor Central', NOW(), NOW()),
	(198, 34, 'Avenida 16 de Fevereiro 122 Shopping Mte Álvaro Piso L1 Loja  - Centro', NOW(), NOW()),
	(199, 146, 'Avenida Joaquim Pacheco de Macedo - Setor Central', NOW(), NOW()),
	(200, 147, 'Avenida Perimetral - Núcleo Habitacional Novo Gama', NOW(), NOW()),
	(201, 463, 'Rua José Castorino de Abreu - Centro', NOW(), NOW()),
	(202, 463, 'Rua José Fabro  - Centro', NOW(), NOW()),
	(203, 463, 'Praça Doutor Euclydes Cardoso Castilho - Centro', NOW(), NOW()),
	(204, 385, 'Rua 25 de agosto - Centro', NOW(), NOW()),
	(205, 221, 'Avenida Marcos Freire - Centro', NOW(), NOW()),
	(206, 264, 'Rua Aleixo Francisco dos Santos - Centro', NOW(), NOW()),
	(207, 93, 'Rua Quinze de Novembro - Centro', NOW(), NOW()),
	(208, 149, 'Avenida Osvaldo Ferreira Sena - Setor Central', NOW(), NOW()),
	(209, 247, 'Rua Quinze de Novembro - Santa Luzia', NOW(), NOW()),
	(210, 201, 'Avenida Oscar Zaiden de Menezes - Centro', NOW(), NOW()),
	(211, 63, 'Praça Pedro Macário - Centro', NOW(), NOW()),
	(212, 20, 'Avenida Barão do Rio Branco  - Centro', NOW(), NOW()),
	(213, 7, 'Rua Prefeito Gilberto Cavalcante - Centro', NOW(), NOW()),
	(214, 464, 'Avenida Ismael - Centro', NOW(), NOW()),
	(215, 465, 'Avenida Vereador Osvaldo Kushida - Centro', NOW(), NOW()),
	(216, 466, 'Rua Hans Clotz - Centro', NOW(), NOW()),
	(217, 467, 'Rua João Maria Conrado 87 Sala  - Centro', NOW(), NOW()),
	(218, 467, 'Avenida Brasil - Centro', NOW(), NOW()),
	(219, 151, 'Avenida do Comércio  - Setor Central', NOW(), NOW()),
	(220, 266, 'Rua Rio de Janeiro - Centro', NOW(), NOW()),
	(221, 152, 'Avenida Irapuan Costa Júnior  - Setor Central', NOW(), NOW()),
	(222, 417, 'Rua John Kennedy 145 Sala 7 e - Centro', NOW(), NOW()),
	(223, 267, 'Rua Manoel Ribas - Centro', NOW(), NOW()),
	(224, 321, 'Rua José Salustiano da Silva  - Centro', NOW(), NOW()),
	(225, 352, 'Rua Ricardo Luiz Cavalcante - Centro', NOW(), NOW()),
	(226, 353, 'Praça Claudino Martins - Centro', NOW(), NOW()),
	(227, 202, 'Avenida Lions Internacional - Centro', NOW(), NOW()),
	(228, 191, 'Rua Celso Magalhães de Almeida  - Centro', NOW(), NOW()),
	(229, 484, 'Travessa da Ana da Fonseca - Centro', NOW(), NOW()),
	(230, 8, 'Rua Doutor Antonio Dorta - Centro', NOW(), NOW()),
	(231, 22, 'Travessa Lourenço de Araujo 552 - Centro', NOW(), NOW()),
	(232, 386, 'Avenida Pinheiro Machado - Centro', NOW(), NOW()),
	(233, 268, 'Rua Pedro Scheidt - Centro', NOW(), NOW()),
	(234, 23, 'Avenida São Pedro  - Centro', NOW(), NOW()),
	(235, 468, 'Rua Sete de Setembro - Centro', NOW(), NOW()),
	(236, 66, 'Avenida Sete de Setembro - Centro', NOW(), NOW()),
	(237, 192, 'Avenida Pedro Dareu - Centro', NOW(), NOW()),
	(238, 295, 'Praça Marechal Castelo Branco - Centro', NOW(), NOW()),
	(239, 387, 'Rua Jonas Antônio de Souza  - Centro', NOW(), NOW()),
	(240, 203, 'Rua Paranatinga - Centro', NOW(), NOW()),
	(241, 269, 'Avenida Coronel Rogério Borba - Centro', NOW(), NOW()),
	(242, 204, 'Avenida José Julio Lima  - Centro', NOW(), NOW()),
	(243, 270, 'Rua Pedro Siqueira - Centro', NOW(), NOW()),
	(244, 323, 'Rua Landri Sales - Centro', NOW(), NOW()),
	(245, 271, 'Rua Rio Amazonas - Centro', NOW(), NOW()),
	(246, 105, 'Rua Major Caetano - Centro', NOW(), NOW()),
	(247, 35, 'Rua Governador José Lindoso  - Centro', NOW(), NOW()),
	(248, 154, 'Rua Coronel Vaiano - Medeiros', NOW(), NOW()),
	(249, 222, 'Rua Barão do Rio Branco - Centro', NOW(), NOW()),
	(250, 400, 'Rua Pedro Daniel Silva - Centro', NOW(), NOW()),
	(251, 272, 'Avenida São Paulo  - Centro', NOW(), NOW()),
	(252, 419, 'Rua Lourenço Vivan  - Centro', NOW(), NOW()),
	(253, 68, 'Avenida da França - Comércio', NOW(), NOW()),
	(254, 250, 'Avenida Victor Engelhard - Centro', NOW(), NOW()),
	(255, 273, 'Avenida Getúlio Vargas  - Centro', NOW(), NOW()),
	(256, 296, 'Rua Padre Cícero - Centro', NOW(), NOW()),
	(257, 69, 'Rua Firmino Alves - Centro', NOW(), NOW()),
	(258, 274, 'Avenida Santos Dumont - Centro', NOW(), NOW()),
	(259, 297, 'Praça da Alegria - Centro', NOW(), NOW()),
	(260, 70, 'Praça Luís Viana Filho - Centro', NOW(), NOW()),
	(261, 205, 'Avenida dos Flávio Luiz  - Centro', NOW(), NOW()),
	(262, 24, 'Avenida Souza Mar - Comercial', NOW(), NOW()),
	(263, 366, 'Rua Doutor Gildásio A. de Oliveira - Prado', NOW(), NOW()),
	(264, 251, 'Avenida Francisco M. de Oliveira - Centro', NOW(), NOW()),
	(265, 275, 'Rua Dona Isabel - Centro', NOW(), NOW()),
	(266, 485, 'Rua João Bebe Agua - Centro', NOW(), NOW()),
	(267, 420, 'Avenida Lions - Centro', NOW(), NOW()),
	(268, 325, 'Rua São João Batista - Centro', NOW(), NOW()),
	(269, 276, 'Rua Corifeu de Azevedo Marques - Centro', NOW(), NOW()),
	(270, 277, 'Praça Santa Cruz - Centro', NOW(), NOW()),
	(271, 278, 'Praça José Maria Soares - Centro', NOW(), NOW()),
	(272, 326, 'Praça Prefeito Jurandir José Duarte - Centro', NOW(), NOW()),
	(273, 367, 'Rua do Comércio - Centro', NOW(), NOW()),
	(274, 207, 'Rua José Salmen Hanze  - Centro', NOW(), NOW()),
	(275, 337, 'Rua Professora Emília Esteves - Centro', NOW(), NOW()),
	(276, 402, 'Avenida Boa Vista - Centro', NOW(), NOW()),
	(277, 421, 'Avenida São Luiz  - Centro', NOW(), NOW()),
	(278, 36, 'Rua Getúlio Vargas  - Centro', NOW(), NOW()),
	(279, 279, 'Avenida Doutor Cícero de Moraes - Centro', NOW(), NOW()),
	(280, 497, 'Avenida JK 150 - Setor Central', NOW(), NOW()),
	(281, 368, 'Avenida Castelo Branco - Centro', NOW(), NOW()),
	(282, 498, 'Avenida Tocantins - Setor Central', NOW(), NOW()),
	(283, 354, 'Rua Euclides Lins de Albuquerque - Centro', NOW(), NOW()),
	(284, 354, 'Praça Barão do Rio Branco - Centro', NOW(), NOW()),
	(285, 298, 'Rua Dom Pedro II - Centro', NOW(), NOW()),
	(286, 298, 'Rua João de Araujo - Centro', NOW(), NOW()),
	(287, 223, 'Avenida João Selvirio de Souza  - Centro', NOW(), NOW()),
	(288, 355, 'Rua Santo Antônio - Centro', NOW(), NOW()),
	(289, 25, 'Quadra BC-04 156 - Vila Primária', NOW(), NOW()),
	(290, 356, 'Rua Joaquim Vicente de Melo - Centro', NOW(), NOW()),
	(291, 338, 'Rua Borges Alfredique - Centro', NOW(), NOW()),
	(292, 157, 'Rua Coronel Vicente Miguel - Setor Central', NOW(), NOW()),
	(293, 499, 'Avenida Sexta Avenida - Setor Central', NOW(), NOW()),
	(294, 37, 'Rua Coronel Garcia - Centro', NOW(), NOW()),
	(295, 357, 'Rua José Ferreira de Lima 51-A - Centro', NOW(), NOW()),
	(296, 500, 'Rua Leonino de Ramos Caiado - Setor Central', NOW(), NOW()),
	(297, 26, 'Rua Mãe Verônica  - Centro', NOW(), NOW()),
	(298, 9, 'Rua Jacinto Gerônimo - Centro', NOW(), NOW()),
	(299, 299, 'Avenida César Borges - Centro', NOW(), NOW()),
	(300, 299, 'Praça Coronel Jeremias Parente de Sá - Centro', NOW(), NOW()),
	(301, 209, 'Praça Treze de Maio - Centro', NOW(), NOW()),
	(302, 422, 'Rua Professor José Abatti - Centro', NOW(), NOW()),
	(303, 195, 'Rua da Salvação - Jerusalém', NOW(), NOW()),
	(304, 158, 'Avenida Goiânia  - Setor Central', NOW(), NOW()),
	(305, 159, 'Rua José Mário da Costa Rezende  - Setor Central', NOW(), NOW()),
	(306, 423, 'Avenida Doze de Maio - Centro', NOW(), NOW()),
	(307, 423, 'Rua Frei Gregório Dalmonte  - Centro', NOW(), NOW()),
	(308, 282, 'Rua Professor Cleto - Centro', NOW(), NOW()),
	(309, 388, 'Avenida Acir José Damasceno - Centro', NOW(), NOW()),
	(310, 389, 'Avenida Paraíso - Centro', NOW(), NOW()),
	(311, 339, 'Praça da República - Centro', NOW(), NOW()),
	(312, 339, 'Rua Bernardo Viana 52 Fundos - Centro', NOW(), NOW()),
	(313, 327, 'Rua Epaminondas Nogueira - Centro', NOW(), NOW()),
	(314, 77, 'Praça Petronílio Lopes - Centro', NOW(), NOW()),
	(315, 469, 'Rua Manoel Parada de Carvalho - Centro', NOW(), NOW()),
	(316, 160, 'Rua da BR-040 - Parque Rio Branco', NOW(), NOW()),
	(317, 424, 'Rua Mamante Danielli 77 Sala - Centro', NOW(), NOW()),
	(318, 470, 'Rua Geraldino de Oliveira - Centro', NOW(), NOW()),
	(319, 106, 'Rua Paulino Francisco Moreira - Centro', NOW(), NOW()),
	(320, 426, 'Avenida São Paulo  - Centro', NOW(), NOW()),
	(321, 426, 'Rua Sidiney Roman - Centro', NOW(), NOW()),
	(322, 196, 'Rua Doutor Nina Rodrigues - Centro', NOW(), NOW()),
	(323, 471, 'Rua Major Correa - Centro', NOW(), NOW()),
	(324, 472, 'Rua Mário Scarvance - Centro', NOW(), NOW()),
	(325, 162, 'Rua Joaquim P. Oliveira - Setor Central', NOW(), NOW()),
	(326, 94, 'Rua Modesto de Mendonça  - Centro', NOW(), NOW()),
	(327, 340, 'Rua Deputado Francelino Bastos França  - Centro', NOW(), NOW()),
	(328, 358, 'Rua 11 de Janeiro - Centro', NOW(), NOW()),
	(329, 358, 'Rua Deputado José Lúcio Ribeiro - Centro', NOW(), NOW()),
	(330, 95, 'Rua José Correia Sobrinho  - Centro', NOW(), NOW()),
	(331, 78, 'Praça Alfredo Navarro - Centro', NOW(), NOW()),
	(332, 79, 'Praça Edvaldo Valois - Centro', NOW(), NOW()),
	(333, 329, 'Avenida Castelo Branco - Centro-Sul', NOW(), NOW()),
	(334, 80, 'Rua Padre Alfredo Haasler - Centro', NOW(), NOW()),
	(335, 473, 'Avenida Fernão Dias Paes Leme - Centro', NOW(), NOW()),
	(336, 341, 'Rua Irmã Maria Agostinha  - Centro', NOW(), NOW()),
	(337, 107, 'Avenida Domingos Perim - Centro', NOW(), NOW()),
	(338, 359, 'Avenida Ministro Aluízio Alves - Centro', NOW(), NOW()),
	(339, 283, 'Avenida Anacleto Bueno de Camargo - Centro', NOW(), NOW()),
	(340, 300, 'Rua Antônio Bilui - Centro', NOW(), NOW()),
	(341, 212, 'Rua Chile - Centro', NOW(), NOW()),
	(342, 474, 'Rua da Rodagem - Centro', NOW(), NOW()),
	(343, 474, 'Rua Monsenhor Paiva - Centro', NOW(), NOW()),
	(344, 474, 'Rua Roberto Gruendling 231 Sala - Centro', NOW(), NOW()),
	(345, 474, 'Rua Doutora Cecília Rangel Janini  - Centro', NOW(), NOW()),
	(346, 284, 'Avenida Pedro Álvares Cabral - Centro', NOW(), NOW()),
	(347, 285, 'Avenida Getúlio Vargas  - Centro', NOW(), NOW()),
	(348, 83, 'Avenida Eujácio Simões - Centro', NOW(), NOW()),
	(349, 225, 'Praça Senhora do Patrocínio - Centro', NOW(), NOW()),
	(350, 226, 'Praça Vereador Fernando S. Melo - Centro', NOW(), NOW()),
	(351, 228, 'Rua Prefeito Wilson Damião - Centro', NOW(), NOW()),
	(352, 303, 'Praça Agamenon Magalhães - Centro', NOW(), NOW()),
	(353, 229, 'Rua Vereador Dumas Chalita - Centro', NOW(), NOW()),
	(354, 197, 'Rua Dois - Centro', NOW(), NOW()),
	(355, 163, 'Rua Felismino Viana 203 Sala - Setor Central', NOW(), NOW()),
	(356, 304, 'Rua Oliveira Estelita - Centro', NOW(), NOW()),
	(357, 369, 'Avenida Rio Branco - Centro', NOW(), NOW()),
	(358, 224, 'Rua Professor Bernardo Baur - Centro', NOW(), NOW()),
	(359, 164, 'Rua Tancredo Neves - Setor Central', NOW(), NOW()),
	(360, 230, 'Avenida Firmino Maia - Centro', NOW(), NOW()),
	(361, 230, 'Avenida Bueno Brandão  - Centro', NOW(), NOW()),
	(362, 230, 'Rua Ozeas Gomes Pinto - Centro', NOW(), NOW()),
	(363, 96, 'Rua Padre José Beviláqua - Centro', NOW(), NOW()),
	(364, 370, 'Avenida Vinte e Cinco de Julho - Centro', NOW(), NOW()),
	(365, 427, 'Rua Constâncio Krummel  - Centro', NOW(), NOW()),
	(366, 428, 'Rua Pedro Andreazza - Centro', NOW(), NOW()),
	(367, 231, 'Praça Dom Delfim - Centro', NOW(), NOW()),
	(368, 213, 'Rua Lino Bispo de Oliveira - Centro', NOW(), NOW()),
	(369, 371, 'Avenida das Flores - Centro', NOW(), NOW()),
	(370, 373, 'Rua General Flores da Cunha - Centro', NOW(), NOW()),
	(371, 374, 'Rua João Batista Becker  - Centro', NOW(), NOW()),
	(372, 109, 'Rua Vasco Fernandes Coutinho - Centro', NOW(), NOW()),
	(373, 166, 'Praça Santo Antônio - Setor Central', NOW(), NOW()),
	(374, 214, 'Avenida Brasil - Setor Norte', NOW(), NOW()),
	(375, 110, 'Rua Maria Dolores Tavares Bonela - Centro', NOW(), NOW()),
	(376, 111, 'Avenida Champagnat - Centro de Vila Velha', NOW(), NOW()),
	(377, 390, 'Avenida Marechal Rondon - Centro (S-01)', NOW(), NOW()),
	(378, 475, 'Rua Manoel Mateus - Capela', NOW(), NOW()),
	(379, 476, 'Rua São João - Centro', NOW(), NOW()),
	(380, 232, 'Avenida Brasil 120 Loja - Centro', NOW(), NOW()),
	(381, 233, 'Rua Crispim Gomes Pinto - Centro', NOW(), NOW()),
	(382, 234, 'Rua Marçal Barbalho  - Centro', NOW(), NOW()),
	(383, 235, 'Rua Prefeito Quim Júlio - Centro', NOW(), NOW()),
	(384, 287, 'Rua XV de Novembro - Centro', NOW(), NOW()),
	(385, 236, 'Rua Major Felicíssimo 256-A - Centro', NOW(), NOW()),
	(386, 375, 'Rua Anibal Negrini - Centro', NOW(), NOW()),
	(387, 477, 'Rua Herculano do Livramento - Centro', NOW(), NOW()),
	(388, 376, 'Rua Romualdo Tarasconi - Centro', NOW(), NOW()),
	(389, 377, 'Avenida Nove de Maio - Centro', NOW(), NOW()),
	(390, 429, 'Rua Sebastião Kammer  - Centro', NOW(), NOW()),
	(391, 112, 'Avenida Jerônimo Monteiro - Centro', NOW(), NOW()),
	(392, 478, 'Rua Doutor Nunes - Centro', NOW(), NOW()),
	(393, 84, 'Avenida Presidente Dutra - Centro', NOW(), NOW()),
	(394, 378, 'Rua dos Imigrantes - Centro', NOW(), NOW()),
	(395, 305, 'Avenida Henrique de Holanda - Matriz', NOW(), NOW()),
	(396, 27, 'Avenida Ayrton Senna - Centro', NOW(), NOW()),
	(397, 256, 'Avenida Manoel Félix de Farias - Centro', NOW(), NOW()),
	(398, 288, 'Avenida Brasil Argentina - Centro', NOW(), NOW()),
	(399, 237, 'Praça Bernardino Rocha - Centro', NOW(), NOW()),
	(400, 342, 'Rua Natal - Morro da Conquista', NOW(), NOW()),
	(401, 479, 'Avenida 31 de Março - Centro', NOW(), NOW()),
	(402, 480, 'Avenida Francisco Vilar Horta - Patrimônio Novo', NOW(), NOW());